production:
  solr:
    hostname: localhost
    port: 8983
    path: /solr/production
    log_level: WARNING

development:
  solr:
    hostname: localhost
    port: 8983
    path: /solr/development
    log_level: INFO

test:
  solr:
    hostname: localhost
    port: 8983
    path: /solr/test
    log_level: WARNING